+incdir+$PRJROOT/verif/dep/common/sv/altr_cmn
+incdir+$PRJROOT/verif/dep/common/sv/avmm
+incdir+$PRJROOT/verif/dep/common/sv/sopc_builder_ip

+incdir+$PRJROOT/verif/sv/ioc_lvds_env
+incdir+$PRJROOT/verif/sv/iic_avmm
+incdir+$PRJROOT/verif/sv/gpio
+incdir+$PRJROOT/verif/sv/uart_svt/src/sverilog/vcs 
+incdir+$PRJROOT/verif/sv/uart_svt/include/sverilog 
+incdir+$PRJROOT/verif/sv/uart_svt/src/verilog/vcs 
+incdir+$PRJROOT/verif/sv/uart_svt/include/verilog 
+incdir+$PRJROOT/verif/sv/uart_env
+incdir+$PRJROOT/verif/sv/smb_mst_env
+incdir+$PRJROOT/verif/sv/pca9555_smb_mst_env
+incdir+$PRJROOT/verif/sv/smb_env
+incdir+$PRJROOT/verif/sv/smb_env/smb_cmd_agt
+incdir+$PRJROOT/verif/sv/smb_env/smb_seqlib
+incdir+$PRJROOT/verif/sv/plt_pwr_env
+incdir+$PRJROOT/verif/sv/mcsi_env
+incdir+$PRJROOT/verif/top/uart_hdl 
+incdir+$PRJROOT/verif/top/env
+incdir+$PRJROOT/verif/top/test
+incdir+$PRJROOT/verif/tests

$PRJROOT/verif/top/dut_cpufpga_wrapper.sv
$PRJROOT/verif/top/dut_scmfpga_wrapper.sv
$PRJROOT/verif/top/dut_debugfpga_wrapper.sv
#$PRJROOT/verif/top/mcsi_cpu_tb_wrapper.sv
#$PRJROOT/verif/top/mcsi_scm_tb_wrapper.sv
#$PRJROOT/verif/top/mcsi_dbg_tb_wrapper.sv
$PRJROOT/verif/top/tb_cosim_pkg.sv
$PRJROOT/verif/tests/cosim_test_pkg.sv
$PRJROOT/verif/top/tb_cosim_rtl.sv
$PRJROOT/verif/top/tb_cosim_sim.sv
#$PRJROOT/verif/top/mcsi_tb_top.sv
#$PRJROOT/verif/top/mcsi_tb_sim.sv
#$PRJROOT/verif/sv/stub/config.sv
