#+incdir+$RTL_PATH/lib/includes
#+incdir+$RTL_PATH/scmfpga/includes
#
#
#$RTL_PATH/scmfpga/quartus_ip/pll_scm/pll_scm.v
#$RTL_PATH/scmfpga/quartus_ip/max10_flash/scm_flash/simulation/submodules/altera_onchip_flash.v
#$RTL_PATH/scmfpga/quartus_ip/max10_flash/scm_flash/simulation/submodules/altera_onchip_flash_avmm_csr_controller.v
#$RTL_PATH/scmfpga/quartus_ip/max10_flash/scm_flash/simulation/submodules/altera_onchip_flash_avmm_data_controller.v
#$RTL_PATH/scmfpga/quartus_ip/max10_flash/scm_flash/simulation/submodules/altera_onchip_flash_util.v
#$RTL_PATH/scmfpga/quartus_ip/max10_flash/scm_flash/simulation/scm_flash.v
#
##$RTL_PATH/scmfpga/quartus_ip/scm_i2c_slave/scm_i2c_slave/simulation/submodules/altera_i2cslave_to_avlmm_bridge.v
##$RTL_PATH/scmfpga/quartus_ip/scm_i2c_slave/scm_i2c_slave/simulation/submodules/altr_i2c_avl_mst_intf_gen.v
##$RTL_PATH/scmfpga/quartus_ip/scm_i2c_slave/scm_i2c_slave/simulation/submodules/altr_i2c_clk_cnt.v
##$RTL_PATH/scmfpga/quartus_ip/scm_i2c_slave/scm_i2c_slave/simulation/submodules/altr_i2c_condt_det.v
##$RTL_PATH/scmfpga/quartus_ip/scm_i2c_slave/scm_i2c_slave/simulation/submodules/altr_i2c_databuffer.v
##$RTL_PATH/scmfpga/quartus_ip/scm_i2c_slave/scm_i2c_slave/simulation/submodules/altr_i2c_rxshifter.v
##$RTL_PATH/scmfpga/quartus_ip/scm_i2c_slave/scm_i2c_slave/simulation/submodules/altr_i2c_slvfsm.v
##$RTL_PATH/scmfpga/quartus_ip/scm_i2c_slave/scm_i2c_slave/simulation/submodules/altr_i2c_spksupp.v
##$RTL_PATH/scmfpga/quartus_ip/scm_i2c_slave/scm_i2c_slave/simulation/submodules/altr_i2c_txout.v
##$RTL_PATH/scmfpga/quartus_ip/scm_i2c_slave/scm_i2c_slave/simulation/submodules/altr_i2c_txshifter.v
##$RTL_PATH/scmfpga/quartus_ip/scm_i2c_slave/scm_i2c_slave/simulation/scm_i2c_slave.v
##$RTL_PATH/scmfpga/src/i2c_slave_bmc_wrapper/i2c_slave_bmc_wrapper.v
##$PRJROOT/verif/sv/stub/scm_i2c_slave.v
#
#
#
#$RTL_PATH/scmfpga/src/plt_logic/scm_aux/scm_aux.v
#$RTL_PATH/scmfpga/src/plt_logic/p5v_main_pwr/p5v_main_pwr.v
#$RTL_PATH/scmfpga/src/plt_logic/dcscm_main/dcscm_main.v
#
#$RTL_PATH/scmfpga/src/scm_csr/general_csr.v
#$RTL_PATH/scmfpga/src/scm_csr/scm_global_csr.v
#$RTL_PATH/scmfpga/src/scm_csr/scm_pfr_csr.v
#
#$RTL_PATH/scmfpga//src/top/scmfpga_top.v
